### ISSUE TITLE
Database.from(<DataSource>) has been removed

### ISSUE THREAD

**Issue by flyaruu** [davidmoten/rxjava2-jdbc#4]
I'm using rxjava-jdbc and I use Database.from(<DataSource>) pretty much everywhere. I'm upgrading to RxJava2 and see that that is no longer possible.

Is this intentional? Is there a straightforward work around?

**Comment by davidmoten** [comment]
We can add that method but in the meantime just make a ConnectionProvider
that delegates to your DataSource.

**Comment by flyaruu** [comment]
Ok, I know create a 'ConnectionProviderFromDataSource' (basically copied from the rxjava1 jdbc impl) that wraps the DataSource, use that when creating a Pool, and pass that when querying a datasource.

Seems to work fine, thanks!

**Comment by davidmoten** [comment]
I will need to add some strategies for using DataSources because they are
normally shared across multiple applications and if you specify a
non-blocking pool then it will not return connections to the container for
use by other applications. I'll have a think about it, suggestions welcome.

**Comment by davidmoten** [comment]
I'll reopen this while I'm working on it. I'll need for starters to do some unit testing with a blocking ConnectionProvider  (and make them easy to create from a DataSource for instance).

**Comment by davidmoten** [comment]
@flyaruu Out of curiosity do you deploy your application to a container so that the DataSource is shared with other applications or is it standalone? 

I've added a method `Database.fromBlocking(DataSource)` to source and it is passing one unit test. I'll add more unit tests over the next couple of days and make a release.

I'll be discussing these options in the README shortly:
* use a NonBlockingPool to reserve a portion or all of the DataSource connections
* use a Blocking connection provider to share connections as normal with other DataSource users (this is the behaviour that rxjava-jdbc uses)

**Comment by flyaruu** [comment]
Right now they are mixed. I'm rewriting part of a legacy application to use a reactive model, perhaps I'll do all of it at some point, but realistically I think it will coexist with blocking calls.

**Comment by davidmoten** [comment]
0.1-RC8 has been released with support for blocking connection providers (like a shared DataSource).

```Database.fromBlocking(DataSource)```

0.1-RC9 will have an overload in the `Pools.nonBlocking()` builder for specifying a `.connectionProvider(DataSource)`.

**Comment by flyaruu** [comment]
Sounds great! I'll have a look at it, thanks!

**Comment by flyaruu** [comment]
Works like a charm!
